### ISSUE TITLE
Partial update making all field to null

### ISSUE THREAD

**Issue by jonathan-bibas** [algolia/algoliasearch-client-java#491]
- Algolia Client Version:2.*
- Language Version:Java Appengine

### Description
Hi, when i user the function `index.partialUpdateObject(objectID,object)`, all field null in my object are null in algolia, it's look like a simple persist function instead of partialUpdate

**Comment by julienbourdeau** [comment]
Hi @jonathan-bibas,
It's the expected behavior because `null` is a valid value that you might want to send to Algolia. In order to only upate the field you want with the `partialUpdateObject` method, you'll have to create a new class, that only holds the field you need.

Please let me know if that works for you 👍

**Comment by jonathan-bibas** [comment]
Your response doesn't help me, but I found a solution:
Use a custom ObjectMapper on algolia and set "ignore null fields"
Here the code:
```
APIClient client = new AppEngineAPIClientBuilder("XXXXXXXXX","XXXXXXXXXXXX")
	.setObjectMapper( 
		new ObjectMapper().
		setSerializationInclusion(Include.NON_NULL))
	.build();
```
