### ISSUE TITLE
"null value not allowed for objectID" exception while saving a new object

### ISSUE THREAD

**Issue by familywiser1** [algolia/algoliasearch-client-java#630]
- Algolia Client Version: 3.2.1
- Language Version: Java

### Description
I am getting `null value not allowed for objectID` exception while saving a new object without manually assigning any objectId (`autoGenerateObjectID` is false)

### Steps To Reproduce

```
class Contact {
  private String firstname;
  private String objectID;
  // Getters/setters ommitted
}

SearchIndex<Contact> index = client.initIndex("contacts", Contact.class);

Contact contact=new Contact();
 contact.setFirstname("Jimmie");
//contact. setObjectID("") 

index.saveObject(contact,true); 


```
The code  above throws following exception
```
com.algolia.search.exceptions.AlgoliaApiException: {"message":"null value not allowed for objectID near line:1 column:238","status":400}
```
However, if I set `objectID` to an empty string, the code works

```
Contact contact=new Contact();
contact.setFirstname("Jimmie");
contact. setObjectID("") 

index.saveObject(contact,true); //it works and I get auto assigned objectId back
```
I don't think the Java SDK should require setting objectId as an empty string.

**Comment by aseure** [comment]
Hello @familywiser1, thank you for reporting us your issue.

There is indeed an issue when you try to `saveObject` your `Contact` instance since the sent payload get serialiazed as:

```json
{
  "requests": [
    {
      "action": "addObject",
      "body": {
        "firstname": "Jimmie",
        "objectID": null
      }
    }
  ]
}
```

and the engine is rejecting `null` values for `objectID` in any case.

When set to `true`, the `autoGenerateObjectID` boolean will ensure that when a record is sent **without** an `objectID`, the Algolia API will not reject the call but instead generate an objectID for it. Again, whether or not the `autoGenerateObjectID` is set, the Algolia API will never accept a `null` value for `objectID`.

Since all your classes are expected to be POJO serialized by Jackson, what you need is to add the `@JsonInclude(Include.NON_NULL)` Jackson annotation on top of your `objectID` member definition, such as:

```java
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

public class Contact {
    private String firstname;

    @JsonInclude(Include.NON_NULL)
    private String objectID;

    // Getters/setters omitted
}
```

This will prevent Jackson to serialize the null `objectID` members of your `Contact` instances.

Let us know if something is still unclear about this, I'll be happy to help.
