### ISSUE TITLE
Partial update making all field to null

### ISSUE THREAD

**Issue by ashuto-sh** [algolia/algoliasearch-client-java#639]
- Algolia Client Version: 3.0.0
- Language Version: Java

### Description
`partialUpdateObject` and its variants sets fields to null. Ideally it should only set the non null values.

https://github.com/algolia/algoliasearch-client-java-2/issues/491#issuecomment-398684011 suggests creating a new class for only the required fields. But this does not seem feasible.
e.g.
Customer {
String a, b, c
}

So to only update `a`, I'll have to create
CustomerA{
String a
}

similarly for updating `b` and `c`
CustomerBC {
String b,c
}

So on so forth.
This seems like a useless boilerplate. Rather than that one could use `saveObject` or one of its variants. But using `saveObject` does not make sense if I have to update only one attribute in an object having 100 attributes, as it would increase request size and in turn restrict batch size.

Another option would be to configure Jackson Objectmapper to ignore nulls, but the current setting makes it too complicated as one has to create Custom SearchClient and override HttpTransport in it.

Would be good to have something to make `partialUpdateObject` usable.

**Comment by Ant-hem** [comment]
Hi,

To solve your issue, you can tell Jackson to ignore null values at the class level:

```java
@JsonInclude(Include.NON_NULL)
class Foo
{
  String bar; // if "bar" is null it wont be serialized
}
```

**Comment by ashuto-sh** [comment]
This means I would have to declare same class twice one with annotation and other without. The one without annotation would be used in `saveObject` and other for `partialUpdateObject`

**Comment by Ant-hem** [comment]
Maybe I am missing something but one class with the annotation will work because for both `saveObject` and `partialUpdateObject` you don't want to save `null` values.

Look at this [Indexing test](https://github.com/algolia/algoliasearch-client-java-2/blob/master/algoliasearch-core/src/test/java/com/algolia/search/integration/index/IndexingTest.java#L131) doing partial update with a [POJO](https://github.com/algolia/algoliasearch-client-java-2/blob/febbaeafd7fbdee4affc9856a4601947a1bd1443/algoliasearch-core/src/test/java/com/algolia/search/integration/models/AlgoliaIndexingObject.java#L8) using the annotation.

**Comment by Ant-hem** [comment]
Closing this one, since issue seems resolved.
Don't hesitate do re-open if needed.
